name: Publish to npm (Manual)

# Diese Action wird nur manuell oder bei Version-Tags ausgelöst
on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Version Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Bump Version (if manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          npm version ${{ inputs.version-type }} -m 'chore: bump version to %s [skip ci]'
          git push --follow-tags

      - name: Build Package
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

